### ISSUE TITLE
An option to turn on whether people see when you join / leave in-game with Premium and Premium+

### ISSUE THREAD

**Issue by PsychoPathhhh** [mcpvp-club/pvp-club#15]
### Description

/settings then there's an option for premium and premium+ users to turn this feature on / off

### Additional context

![image](https://github.com/user-attachments/assets/aaf7cc1d-69a3-4edc-a70c-f5fc58eda536)

### Checklist

- [X] I have checked for any identical suggestions already open.

**Comment by Jyguy** [comment]
Added, will be applied next restart!
