### ISSUE TITLE
Display the amount of Golden Apples remaining after an UHC duel

### ISSUE THREAD

**Issue by ProfX33** [mcpvp-club/pvp-club#16]
### Description

Likewise to the display that pops up at the end of pot / nethpot fights displaying the amount of potions remaining for each player, at the end of an UHC duel it should show the amount of Golden Apples each player had left.
Knowing the amount of Golden Apples your opponent had left is would be a great way of knowing how well you did against them / how close the round was.

### Checklist

- [X] I have checked for any identical suggestions already open.

**Comment by Jyguy** [comment]
Thanks for the suggestion, it will be applied next restart!
