### ISSUE TITLE
Pot counts at the end of pot/netheritepot duels are always 0

### ISSUE THREAD

**Issue by Jyguy** [mcpvp-club/pvp-club#20]
### Describe the bug

The remaining potion counts will always show `0 | 0` no matter how many potions each player has.

### Expected behavior

The counts should reflect the amount of potions left in each player's inventory.

### To reproduce

1. Duel a player in Pot or Netheritepot
2. At the end of the round, observe the pot counts

### Checklist

- [X] I have checked for any identical bug reports already open.

**Comment by ProfX33** [comment]
![image](https://github.com/user-attachments/assets/0fe385e4-2a5c-4219-84a5-a3937604ccb3)
The totem count after crystal duels also doesn't seem to work correctly. (It always shows -1 for the player that won)
Not sure if this is related to the issue you described but it should also be fixed.

**Comment by Jyguy** [comment]
> ![image](https://private-user-images.githubusercontent.com/132227792/357576014-0fe385e4-2a5c-4219-84a5-a3937604ccb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2Mjk1NzksIm5iZiI6MTcyMzYyOTI3OSwicGF0aCI6Ii8xMzIyMjc3OTIvMzU3NTc2MDE0LTBmZTM4NWU0LTJhNWMtNDIxOS04NGE1LWEzOTM3NjA0Y2NiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwOTU0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzZmMzU1NjZhNWE3MGM4MmU5NGQ2NGVkMDFlM2JmNGYyYzk4YTFjNjgyM2I5ZmQwZWZhNzk0ZjcwOTIzMDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8pFZWH1Hz8p1adYA-XBcckGctoIfTBwwDVJM2ymfkWo) The totem count after crystal duels also doesn't seem to work correctly. (It always shows -1 for the player that won) Not sure if this is related to the issue you described but it should also be fixed.

This is a separate issue; has been fixed, will be applied next restart

**Comment by Jyguy** [comment]
This was fixed at some point, likely from a server build / version update.
