### ISSUE TITLE
There should be no KB1 sword in the default Nethpot queue kit

### ISSUE THREAD

**Issue by ProfX33** [mcpvp-club/pvp-club#21]
### Description

When you queue into a netherite pot duel with the sign you get a nethpot kit that includes both a normal sword and a sword enchanted with knockback 1.
Since the official tierlist kit only has one sword without knockback, the knockback 1 sword should be removed by default. It is very frustrating when you want to practice tierlist nethpot and many other players simply use the knockback 1 sword against you, which gives an objective advantage.
Players should however still be given the option to chose between kb1 or not when doing /duel (as it currently is).

### Checklist

- [X] I have checked for any identical suggestions already open.

**Comment by Jyguy** [comment]
Added!
