### ISSUE TITLE
FAQ Request

### ISSUE THREAD

**Issue by Gowthr** [mcpvp-club/pvp-club#26]
### Description

The pvpclub Discord does not contain an entry for `/editechest` or `/editshulker` leaving much confusion about how they function.

### Additional context

![image](https://github.com/user-attachments/assets/bbc3a020-c977-4af5-9da4-459cf5e48655)
![image](https://github.com/user-attachments/assets/0beaed87-7af2-4673-a181-c18908e15222)

### Checklist

- [X] I have checked for any identical suggestions already open.

**Comment by Jyguy** [comment]
Done, thanks for the suggestion!
